services:
  - type: web
    name: plant-disease-detection-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 180
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: HF_MODEL_REPO_ID
        sync: false
      - key: HF_MODEL_FILENAME
        value: plant_disease_model_1_latest.pt
      - key: CORS_ALLOWED_ORIGINS
        sync: false
